#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: all
  become: true
  become_user: root
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
      retries: 3

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
      retries: 3

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      retries: 3

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      retries: 3

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      retries: 3

    - name: Install Docker Module for Python
      pip:
        name: docker
      retries: 3

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
      retries: 3

    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: started
        ports:
          - 80:80
        detach: "yes"
      with_sequence: count={{ create_containers }}
      retries: 3
